### ISSUE TITLE
Pages with TOC and Sub-Pages Fail to be Converted Correctly

### ISSUE THREAD

**Issue by dfhawthorne** [dfhawthorne/dfhawthorne.github.io#34]
The web page, `docs/home/11g-oce-rac.html`, fails to be displayed by Jekyll with the following messages:

```text
      Regenerating: 1 file(s) changed at 2024-03-01 21:27:00
                    home/11g-oce-rac.html
YAML Exception reading /home/douglas/git-repositories/dfhawthorne.github.io/docs/home/11g-oce-rac.html: (<unknown>): mapping values are not allowed in this context at line 12 column 44 
  Liquid Exception: Liquid error (line 5): undefined variable title in /home/douglas/git-repositories/dfhawthorne.github.io/docs/_layouts/default.html
             Error: Liquid error (line 5): undefined variable title
             Error: Run jekyll build --trace for more information.
```

The TOC was converted incorrectly:

```yaml
table-of-contents:
- toc-url: Section-1---Grid-Infrastructure:-Clusterware-and-ASM.html
  toc-text: Section 1 - Grid Infrastructure: Clusterware and ASM
- toc-url: Section-2---Real-Application-Clusters.html
  toc-text: Section 2 - Real Application Clusters
---
```

**Comment by dfhawthorne** [comment]
The problem with the Liquid error was the presence of the isolated hyphen in the `toc-text` variable.

**Comment by dfhawthorne** [comment]
First, correct the extraction of the TOC:

```bash
hxnormalize -xe docs/home/11g-oce-rac.html | \
    hxremove script, '#sites-chrome-sidebar-left' | \
    hxselect .sites-embed-toc-maxdepth-6 | \
   head
```

The first few lines are:

```html
<div class="goog-toc sites-embed-toc-maxdepth-6">
                                                  <p> Contents</p>

                                                  <ol class="goog-toc">
                                                    <li class="goog-toc"> <a href="11g-oce-rac.html#TOC-Section-1---Grid-Infrastructure:-Clusterware-and-ASM"> <strong> 1
                                                      </strong>
                                                      Section 1 - Grid
                                                      Infrastructure:
                                                      Clusterware and
                                                      ASM </a>
```

**Comment by dfhawthorne** [comment]
No sub-pages widget was found. The trace log shows:

```text
sub_pages_widget_found   = False
subsequent_content_found = False
sub_page: None
No sub-page widget found.
```

**Comment by dfhawthorne** [comment]
TOC in Classic Google Sites version appears after two (2) paragraphs. The TOC should not be converted.

**Comment by dfhawthorne** [comment]
`docs/home/11g-oce-ra.html` has two (2) TOC widgets

**Comment by dfhawthorne** [comment]
Updated CSS to reflect Classic Google Sites. `docs/_sass/_content.scss` updated with:

```css
div.goog-toc p {
    padding: 4px 5px 0;
    margin: 0;
    font-weight: bold;
    }

div.goog-toc {
    background:none;
    border: 1px solid #ccc;
}
```

Updated the conversion script, `scripts/convert_web_page.py`, to decode the structure of the input HTML file into four (4) elements:

1. Prologue (displayable text at start of main content)
1. TOC (Table of Contents)
   - optional `div` tag with a class of `sites-embed-toc-maxdepth-6`
1. Sub-pages Menu
   - optional `div` with an `ID` of `sites-toc-undefined`
1. Epilogue (displayable text after optional elements)

The TOC is not converted to YAML format if either:

1. There is displayable text preceding the TOC entries (prologue)
1. There are multiple TOCs found

`home/11g-oce-rac.html` was successfully converted.
