### ISSUE TITLE
Incorrect Sub-Pages Menu for 12C OCP Upgrade Anchor Page

### ISSUE THREAD

**Issue by dfhawthorne** [dfhawthorne/dfhawthorne.github.io#52]
After conversion, `docs/home/12c-ocp-upgrade.html`, shows only one (1) level in the sub-pages menu instead of three (3):

```yaml
sub-pages-title: 'Exam Topics'
sub-pages:
- title: 'Section 1: New Features of Oracle Database 12c'
  url: home/12c-ocp-upgrade/section-1-new-features-of-oracle-database-12c.html
- title: 'Section 2: Key DBA Skills'
  url: home/12c-ocp-upgrade/section-2-key-dba-skills.html
---
```
