### ISSUE TITLE
CRONULLA System Build Journal - Mismatch between title and file names

### ISSUE THREAD

**Issue by dfhawthorne** [dfhawthorne/dfhawthorne.github.io#88]
The sub-pages element in `docs/home/system-builds/cronulla.html` shows a difference between the file names and titles:

```yaml
sub-pages:
- title: '2014-03-03 Design'
  url: home/system-builds/cronulla/00-design.html
- title: '2014-03-04 Create VM'
  url: home/system-builds/cronulla/01-create-vm.html
- title: '2014-03-06 Fix OS Install Issues'
  url: home/system-builds/cronulla/02-fix-os-install-issues.html
- title: '2014-03-09 Install OMS 12.1.0.3.1 Again'
  url: home/system-builds/cronulla/06-install-oms-12-1-0-3-1-again.html
- title: '2014-03-14 Complete OMS 12.1.0.3.1 Installation'
  url: home/system-builds/cronulla/07-complete-oms-12-1-0-3-1-installation.html
- title: '2014-03-16 Configure Firewall Rules'
  url: home/system-builds/cronulla/08-configure-firewall-rules.html
- title: '2014-04-14 Apply WLS Patches'
  url: home/system-builds/cronulla/10-apply-wls-patches.html
- title: '2014-04-19 0 Additional Configuration Tasks'
  url: home/system-builds/cronulla/09-additional-configuration-tasks.html
- title: '2014-04-19 1 Install Guest Additions'
  url: home/system-builds/cronulla/11-install-guest-additions.html
- title: '2014-04-26 0 Install RDA and EMDIAG Tools'
  url: home/system-builds/cronulla/12-install-rda-and-emdiag-tools.html
- title: '2014-04-26 1 Patch OMS to 12.1.0.3.2'
  url: home/system-builds/cronulla/13-patch-oms-to-12-1-0-3-2.html
- title: '2014-05-24 0 Prepare to Install OMS 12.1.0.3.1'
  url: home/system-builds/cronulla/03-prepare-to-install-oms-12-1-0-3-1.html
- title: '2014-05-24 1 Install OMS 12.1.0.3.1'
  url: home/system-builds/cronulla/04-install-oms-12-1-0-3-1.html
- title: '2014-05-24 2 Add Extra Disk Space'
  url: home/system-builds/cronulla/05-add-extra-disk-space.html
- title: '2014-05-24 3 Apply WLS Patches'
  url: home/system-builds/cronulla/14-apply-wls-patches.html
- title: '2014-06-17 Integrate BI Publisher into OEM'
  url: home/system-builds/cronulla/15-integrate-bi-publisher-into-oem.html
- title: '2014-06-29 0 Upgrade OMS 12.1.0.4.0'
  url: home/system-builds/cronulla/16-upgrade-oms-12-1-0-4-0.html
- title: '2014-06-29 1 Upgrade BIP'
  url: home/system-builds/cronulla/17-upgrade-bip.html
- title: '2014-06-29 2 Patch WLS After OMS 12.1.0.4'
  url: home/system-builds/cronulla/18-patch-wls-after-oms-12-1-0-4.html
- title: '2015-06-15 Re-install as VM on Victoria'
  url: home/system-builds/cronulla/19-re-install-as-vm-on-victoria.html
- title: '2015-06-20 Install Packages'
  url: home/system-builds/cronulla/20-install-packages.html
- title: '2015-09-07 Install OMS 12.1.0.4'
  url: home/system-builds/cronulla/21-install-oms-12-1-0-4.html
- title: '2015-10-10 Replace OMR'
  url: home/system-builds/cronulla/22-replace-omr.html
- title: '2020-01-28 Updated .bashrc for OMS and OPMN'
  url: home/system-builds/cronulla/2020-01-28-updated-bashrc-for-oms-and-opmn.html
```

For example, the first sub-element should be:

```yaml
- title: '2014-03-03 Design'
  url: home/system-builds/cronulla/2014-03-03-design.html
```
